### ISSUE TITLE
x-amzn-errortype: ForbiddenException

### ISSUE THREAD

**Issue by TheLittleNaruto** [gettyimages/gettyimages-api#1]
I am testing Search API using curl

`curl -i -H "Api-Key:xxxxxxxxxxxx" "https://api.gettyimages.com/v3/search/images?phrase=books"`
And response is not as expected:

```
HTTP/2 403 
content-type: application/json
content-length: 23
date: Mon, 10 Feb 2020 19:02:24 GMT
x-amzn-requestid: 6d42d68e-5c0a-44d6-9ef5-a8e0e4760067
x-amzn-errortype: ForbiddenException
x-amz-apigw-id: HsdOBGRPPHcFVyg=
x-cache: Error from cloudfront
via: 1.1 30679409511c27f2f2de20e193b58ee5.cloudfront.net (CloudFront)
x-amz-cf-pop: MAA50-C1
x-amz-cf-id: 8bCpl4HrgbhkjPk-AEvDmlpKpAd0UUNYSMfLnNfBGG_hT-KqBVJNzw==
```
The error is not much clear. As per documentation it should come either of these errors:

1. "Account Inactive"
2. "Account Over Queries Per Second Limit"
3. "Account Over Rate Limit"

Any help?

**Comment by mapitman** [comment]
Hello,
It looks like you may be using an expired Sandbox key? Sandbox keys created on our site are no longer active. Getty Images is no longer providing API keys through the registration process on our developer website. If you still wish to have test access to our API, please contact our Sales team at enterprisesolutionssales@gettyimages.com to discuss licensing options or to receive an API key connected to your existing license agreement.
Thanks,
Getty Images API team
