### ISSUE TITLE
Are there API for contributor photo upload? 

### ISSUE THREAD

**Issue by cutecutecat** [gettyimages/gettyimages-api#6]
I want to create an open source gallery tool like `Deepmeta` or `QHero`. After I reviewed API document, I found there is no photo upload API at all? 

Did I miss anything？Or if not, I hope relevant API could be added in the future. Do you have any plan about it?

Thank you!

**Comment by mattdahlgren** [comment]
Hi, thanks for the request. We do not provide an open API for image upload at this time and currently have no firm plans to do so.

Matt
Product Manager
Getty Images
