### ISSUE TITLE
OAuth Token Cache

### ISSUE THREAD

**Issue by jakob-stoeck** [gettyimages/gettyimages-api#61]
`Credentials::getAuthenticationDetails` states `Note: This is a cached operation.` but it is not. On every request the auth token is requested again. Or am I missing something? Is the oauth token caching to be done outside of the ConnectSDK?

**Comment by CaseyMacPherson** [comment]
If you have the latest version of the SDK it does cache the token details. It just doesn't cache them globally between page requests. So subsequent requests force the SDK object to new up again. If your workflow needs to call multiple operations as part of a single page request, then it will cache properly. If you want to persist your credential between page requests, then you'll need to figure out how to cache the value and pass it into the SDK when you construct it.
