### ISSUE TITLE
Don't show api key or api key secret id.

### ISSUE THREAD

**Issue by patugosavi** [gettyimages/gettyimages-api#8]
I am register gettyimages and want to use api but I don't show authentication credentials on my login. I am  send request but no anyone reply.

**Comment by shon-cf** [comment]
@patugosavi did you managed to understand where to get the `api_key` and the `api_secret` ??

**Comment by mapitman** [comment]
Getty Images customers with a paid subscription can be provided access to our API. Please contact your sales rep for more information.
